"""empty message

Revision ID: a0d9146a46a8
Revises: 59a8e5112071
Create Date: 2019-05-01 22:04:09.740473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d9146a46a8'
down_revision = '59a8e5112071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partida', 'siglaMandante')
    op.drop_column('partida', 'siglaVisitante')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partida', sa.Column('siglaVisitante', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('partida', sa.Column('siglaMandante', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
